version: "2"

services:

  composer:
    image: composer
    volumes:
      - ./:/app
    command: composer install --ignore-platform-reqs

  test:
    build:
      context: docker/php
    volumes:
      - ./:/app
    tty: true
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=homestead
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    links:
      - db
#    command: /app/vendor/bin/phpunit -c /app/phpunit.xml
    command: bash

  db:
    image: mysql:5.5.57
    ports:
      - 3309:3306
    environment:
      MYSQL_DATABASE: homestead
      #      MYSQL_USER: root
      #      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: secret